export const routeMeta = [
  { pattern: '/dashboard', title: 'Resumen General' },
  { pattern: '/catalogo/nuevo', title: 'Nuevo Producto' },
  { pattern: '/catalogo/editar/:id', title: 'Editar Producto' },
  { pattern: '/catalogo', title: 'Catálogo de Productos' },
  { pattern: '/inventario/movimientos', title: 'Movimientos' },
  { pattern: '/inventario/nuevo-movimiento', title: 'Nuevo Movimiento' },
  { pattern: '/inventario/nueva-entrada', title: 'Nueva Entrada' },
  { pattern: '/inventario/nueva-salida', title: 'Nueva Salida' },
  { pattern: '/inventario/ajustes', title: 'Ajustes de Inventario' },
  { pattern: '/inventario/conteos', title: 'Conteos Físicos' },
  { pattern: '/inventario/aprobaciones', title: 'Aprobaciones de Inventario' },
  { pattern: '/inventario/movimientos/:id', title: 'Detalle del Movimiento' },
  { pattern: '/inventario/alertas', title: 'Alertas de Stock' },
  { pattern: '/inventario', title: 'Inventario' },
  { pattern: '/ventas/nueva', title: 'Nueva Venta' },
  { pattern: '/ventas', title: 'Ventas' },
  { pattern: '/compras/nueva', title: 'Nueva Compra' },
  { pattern: '/compras/nueva-solicitud', title: 'Nueva Solicitud de Compra' },
  { pattern: '/compras/borradores', title: 'Borradores de Compra' },
  { pattern: '/compras/solicitudes/:id/editar', title: 'Editar Borrador de Compra' },
  { pattern: '/compras/solicitudes/:id', title: 'Detalle de Solicitud' },
  { pattern: '/compras/solicitudes', title: 'Historial de Compras' },
  { pattern: '/compras', title: 'Historial de Compras' },
  { pattern: '/entradas', title: 'Entradas' },
  { pattern: '/salidas', title: 'Salidas' },
  { pattern: '/proveedores/nuevo', title: 'Nuevo Proveedor' },
  { pattern: '/proveedores/editar/:id', title: 'Editar Proveedor' },
  { pattern: '/proveedores/:id', title: 'Detalle del Proveedor' },
  { pattern: '/proveedores', title: 'Proveedores' },
  { pattern: '/configuracion', title: 'Configuración' },
  { pattern: '/reportes', title: 'Reportes · Resumen General' },
]
